# These are supported funding model platforms

# github: [GitHub username, GitHub username]
# patreon: # Replace with up to 4 Patreon usernames
# open_collective: # Replace with up to 4 Open Collective usernames
# ko_fi: # Replace with up to 4 Ko-fi usernames
# tidelift: # Replace with up to 4 Tidelift platform-names/package-names e.g., npm/babel
# community_bridge: # Replace with up to 4 Community Bridge project-names e.g., cloud-foundry
# liberapay: # Replace with up to 4 Liberapay usernames
# issuehunt: # Replace with up to 4 IssueHunt usernames
# otechie: # Replace with up to 4 Otechie usernames
# lfx_crowdfunding: # Replace with up to 4 LFX Crowdfunding project-names e.g., cloud-foundry
# polar: # Replace with up to 4 Polar project-names e.g., cloud-foundry

# For any of the above, comment out the line or leave blank to disable it
# To disable the funding link entirely, delete this file

# For this educational project, contributions are appreciated but not required
# If you'd like to support the development of educational resources:
# - Star the repository
# - Share it with others
# - Contribute code, documentation, or improvements
